version: 2

updates:
  - package-ecosystem: 'github-actions'
    open-pull-requests-limit: 5
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
      eslint:
        patterns:
          - '@tanstack/eslint-*'
          - '@typescript-eslint/*'
          - 'eslint-plugin-*'
          - 'eslint'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
      react-router:
        patterns:
          - 'react-router'
          - 'react-router-dom'
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook-*'
          - 'storybook'
