version: 2

updates:
  - package-ecosystem: 'github-actions'
    open-pull-requests-limit: 1
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all-actions:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    # disable package updates to only allow security updates
    # see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    # see: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
    open-pull-requests-limit: 0
    directory: '/'
    exclude-paths:
      - 'examples/**'
    schedule:
      interval: 'daily'
    groups:
      all-security-updates:
        applies-to: security-updates
        patterns:
          - '*'
