services:
    mgo:
        container_name: mgo
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT-8000}
                - IGNORE_MISSING_TRANSLATIONS
                - LOAD_URL
                - DVA_URL
        ports:
            - ${PORT:-8000}:8080
