/* c8 ignore start */
import type { OrganisationSearchResponse } from '$/types/Organisation';

const searchResponse: OrganisationSearchResponse = {
    organizations: [
        {
            display_name: 'Apothekersgroep Amsterdam Oost V.O.F.',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02008667',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Helmholtzstraat 57\r\n1098LE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Helmholtzstraat 57'],
                    geolocation: {
                        latitude: 124477.269,
                        longitude: 484789.731,
                    },
                    postalcode: '1098LE',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Apothekersgroep Amsterdam Oost V.O.F.',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02010256',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Helmholtzstraat 57\r\n1098LE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Helmholtzstraat 57'],
                    geolocation: {
                        latitude: 124477.269,
                        longitude: 484789.731,
                    },
                    postalcode: '1098LE',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Linnaeusstraat 81\r\n1093EK AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Linnaeusstraat 81'],
                    geolocation: {
                        latitude: 123572,
                        longitude: 485869,
                    },
                    postalcode: '1093EK',
                    state: undefined,
                    type: 'physical',
                },
                {
                    active: true,
                    address: 'Tweede Oosterparkstraat 274-a\r\n1092 BV AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: undefined,
                    lines: ['Tweede Oosterparkstraat 274-a'],
                    geolocation: undefined,
                    postalcode: '1092 BV',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
                {
                    code: 'Z001',
                    display_name: 'Apotheek',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/organization-type',
                },
                {
                    code: 'J8',
                    display_name: 'Openbare apotheek',
                    type: 'http://nictiz.nl/fhir/NamingSystem/organization-type',
                },
            ],
        },
        {
            display_name: 'Staatslieden Apotheek',
            identification_type: 'agb-z',
            identification_value: '17083036',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Van Hallstraat 200\r\n1051HL AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Van Hallstraat 200'],
                    geolocation: {
                        latitude: 119880,
                        longitude: 488144,
                    },
                    postalcode: '1051HL',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '17',
                    display_name: 'Rechtspersonen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Apollo Dental Care B.V.',
            identification_type: 'agb-z',
            identification_value: '12061605',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Apollolaan 86\r\n1077BE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Apollolaan 86'],
                    geolocation: {
                        latitude: 120345,
                        longitude: 484893,
                    },
                    postalcode: '1077BE',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Apollolaan 86\r\n1077BE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Apollolaan 86'],
                    geolocation: {
                        latitude: 120345,
                        longitude: 484893,
                    },
                    postalcode: '1077BE',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '12',
                    display_name: 'Tandartsen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Apollo Dental Care B.V.',
            identification_type: 'agb-z',
            identification_value: '71030342',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Apollolaan 86\r\n1077BE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Apollolaan 86'],
                    geolocation: {
                        latitude: 120345,
                        longitude: 484893,
                    },
                    postalcode: '1077BE',
                    state: undefined,
                    type: 'physical',
                },
                {
                    active: true,
                    address: 'Apollolaan 86\r\n1077BE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Apollolaan 86'],
                    geolocation: {
                        latitude: 120345,
                        longitude: 484893,
                    },
                    postalcode: '1077BE',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '12',
                    display_name: 'Tandartsen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'A.P. Timmers',
            identification_type: 'agb-z',
            identification_value: '12062197',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Hilversumstraat 74\r\n1024KA AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Hilversumstraat 74'],
                    geolocation: {
                        latitude: 126008,
                        longitude: 489273,
                    },
                    postalcode: '1024KA',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '12',
                    display_name: 'Tandartsen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'A.P. Timmers',
            identification_type: 'agb-z',
            identification_value: '71030745',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Hilversumstraat 74\r\n1024KA AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Hilversumstraat 74'],
                    geolocation: {
                        latitude: 126008,
                        longitude: 489273,
                    },
                    postalcode: '1024KA',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '12',
                    display_name: 'Tandartsen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Klitsie Dental',
            identification_type: 'agb-z',
            identification_value: '12098884',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Eerste Rozendwarsstraat 112\r\n1016PC AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Eerste Rozendwarsstraat 112'],
                    geolocation: {
                        latitude: 120498,
                        longitude: 487344,
                    },
                    postalcode: '1016PC',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '12',
                    display_name: 'Tandartsen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Apneu en Tandheelkunde Amsterdam',
            identification_type: 'agb-z',
            identification_value: '71121665',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Louwesweg 6\r\n1066EC AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Louwesweg 6'],
                    geolocation: {
                        latitude: 116664,
                        longitude: 484556,
                    },
                    postalcode: '1066EC',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '12',
                    display_name: 'Tandartsen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Aphrodite Cares',
            identification_type: 'agb-z',
            identification_value: '41418951',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Karthuizersstraat 87\r\n1015LN AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Karthuizersstraat 87'],
                    geolocation: {
                        latitude: 120581,
                        longitude: 488004,
                    },
                    postalcode: '1015LN',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '41',
                    display_name: 'ZZP-ers in wijkverpleging/ PGB aanbieders / Beheerstichtingen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Aphrodite Cares',
            identification_type: 'agb-z',
            identification_value: '71139324',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Karthuizersstraat 87\r\n1015LN AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Karthuizersstraat 87'],
                    geolocation: {
                        latitude: 120581,
                        longitude: 488004,
                    },
                    postalcode: '1015LN',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Karthuizersstraat 87\r\n1015LN AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Karthuizersstraat 87'],
                    geolocation: {
                        latitude: 120581,
                        longitude: 488004,
                    },
                    postalcode: '1015LN',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '41',
                    display_name: 'ZZP-ers in wijkverpleging/ PGB aanbieders / Beheerstichtingen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Apothekersgroep Amsterdam Oost V.O.F.',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02008633',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Helmholtzstraat 57\r\n1098LE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Helmholtzstraat 57'],
                    geolocation: {
                        latitude: 124477.269,
                        longitude: 484789.731,
                    },
                    postalcode: '1098LE',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Linnaeusstraat 81\r\n1093 EK AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: undefined,
                    lines: ['Linnaeusstraat 81'],
                    geolocation: undefined,
                    postalcode: '1093 EK',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
                {
                    code: 'Z001',
                    display_name: 'Apotheek',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/organization-type',
                },
                {
                    code: 'J8',
                    display_name: 'Openbare apotheek',
                    type: 'http://nictiz.nl/fhir/NamingSystem/organization-type',
                },
            ],
        },
        {
            display_name: 'Apegatje',
            identification_type: 'agb-z',
            identification_value: '41785911',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Mr. P.N. Arntzeniusweg 116H\r\n1098GT AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Mr. P.N. Arntzeniusweg 116H'],
                    geolocation: {
                        latitude: 124375,
                        longitude: 485165,
                    },
                    postalcode: '1098GT',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '41',
                    display_name: 'ZZP-ers in wijkverpleging/ PGB aanbieders / Beheerstichtingen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Apegatje',
            identification_type: 'agb-z',
            identification_value: '71174709',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Mr. P.N. Arntzeniusweg 116H\r\n1098GT AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Mr. P.N. Arntzeniusweg 116H'],
                    geolocation: {
                        latitude: 124375,
                        longitude: 485165,
                    },
                    postalcode: '1098GT',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Mr. P.N. Arntzeniusweg 116H\r\n1098GT AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Mr. P.N. Arntzeniusweg 116H'],
                    geolocation: {
                        latitude: 124375,
                        longitude: 485165,
                    },
                    postalcode: '1098GT',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '41',
                    display_name: 'ZZP-ers in wijkverpleging/ PGB aanbieders / Beheerstichtingen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Staatslieden Apotheek',
            identification_type: 'agb-z',
            identification_value: '76089407',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Van Hallstraat 200\r\n1051HL AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Van Hallstraat 200'],
                    geolocation: {
                        latitude: 119880,
                        longitude: 488144,
                    },
                    postalcode: '1051HL',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '76',
                    display_name: 'Leveranciers Hulpmiddelen',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'APG PRAKTIJK VOOR ZELFONDERZOEK&ZELFBEPALING',
            identification_type: 'agb-z',
            identification_value: '71073794',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Willemsparkweg 172\r\n1071HT AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Willemsparkweg 172'],
                    geolocation: {
                        latitude: 119774,
                        longitude: 485468,
                    },
                    postalcode: '1071HT',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '94',
                    display_name: 'Psychologische Zorgverleners',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Staatslieden Apotheek',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02008642',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Van Hallstraat 200\r\n1051HL AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Van Hallstraat 200'],
                    geolocation: {
                        latitude: 119880,
                        longitude: 488144,
                    },
                    postalcode: '1051HL',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Haarlemmerdijk 149\r\n1013 KH AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: undefined,
                    lines: ['Haarlemmerdijk 149'],
                    geolocation: undefined,
                    postalcode: '1013 KH',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
                {
                    code: 'Z001',
                    display_name: 'Apotheek',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/organization-type',
                },
                {
                    code: 'J8',
                    display_name: 'Openbare apotheek',
                    type: 'http://nictiz.nl/fhir/NamingSystem/organization-type',
                },
            ],
        },
        {
            display_name: 'Staatslieden Apotheek',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02082708',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Frederik Hendrikstraat 47\r\n1052HK AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Frederik Hendrikstraat 47'],
                    geolocation: {
                        latitude: 120061,
                        longitude: 487724,
                    },
                    postalcode: '1052HK',
                    state: undefined,
                    type: 'physical',
                },
                {
                    active: true,
                    address: 'Van Hallstraat 200\r\n1051HL AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Van Hallstraat 200'],
                    geolocation: {
                        latitude: 119880,
                        longitude: 488144,
                    },
                    postalcode: '1051HL',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Frederik Hendrikstraat 47\r\n1052 HK AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: undefined,
                    lines: ['Frederik Hendrikstraat 47'],
                    geolocation: undefined,
                    postalcode: '1052 HK',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
                {
                    code: 'Z001',
                    display_name: 'Apotheek',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/organization-type',
                },
                {
                    code: 'J8',
                    display_name: 'Openbare apotheek',
                    type: 'http://nictiz.nl/fhir/NamingSystem/organization-type',
                },
            ],
        },
        {
            display_name: 'Staatslieden Apotheek',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02008618',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Van Hallstraat 200\r\n1051HL AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Van Hallstraat 200'],
                    geolocation: {
                        latitude: 119880,
                        longitude: 488144,
                    },
                    postalcode: '1051HL',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Van Hallstraat 200\r\n1051 HL AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: undefined,
                    lines: ['Van Hallstraat 200'],
                    geolocation: undefined,
                    postalcode: '1051 HL',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
                {
                    code: 'Z001',
                    display_name: 'Apotheek',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/organization-type',
                },
                {
                    code: 'J8',
                    display_name: 'Openbare apotheek',
                    type: 'http://nictiz.nl/fhir/NamingSystem/organization-type',
                },
            ],
        },
        {
            display_name: 'Apotheose Apotheek Spuistraat',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02082642',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Kamerlingh Onneslaan 42\r\n1171AG BADHOEVEDORP',
                    city: 'BADHOEVEDORP',
                    country: 'NEDERLAND',
                    lines: ['Kamerlingh Onneslaan 42'],
                    geolocation: {
                        latitude: 113492.085,
                        longitude: 484049.358,
                    },
                    postalcode: '1171AG',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Spuistraat 239C\r\n1012VP AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Spuistraat 239C'],
                    geolocation: {
                        latitude: 121099,
                        longitude: 487131,
                    },
                    postalcode: '1012VP',
                    state: undefined,
                    type: 'physical',
                },
                {
                    active: true,
                    address: 'Spuistraat 239-c\r\n1012 VP AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: undefined,
                    lines: ['Spuistraat 239-c'],
                    geolocation: undefined,
                    postalcode: '1012 VP',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
                {
                    code: 'Z001',
                    display_name: 'Apotheek',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/organization-type',
                },
                {
                    code: 'J8',
                    display_name: 'Openbare apotheek',
                    type: 'http://nictiz.nl/fhir/NamingSystem/organization-type',
                },
            ],
        },
        {
            display_name: 'Apotheose Apotheek Spuistraat',
            identification_type: 'agb-z',
            identification_value: '71134993',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Spuistraat 239C\r\n1012VP AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Spuistraat 239C'],
                    geolocation: {
                        latitude: 121099,
                        longitude: 487131,
                    },
                    postalcode: '1012VP',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'Apothekersgroep Amsterdam Oost V.O.F.',
            identification_type: 'agb-z',
            identification_value: 'zorgring_02008622',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Helmholtzstraat 57\r\n1098LE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Helmholtzstraat 57'],
                    geolocation: {
                        latitude: 124477.269,
                        longitude: 484789.731,
                    },
                    postalcode: '1098LE',
                    state: undefined,
                    type: 'postal',
                },
                {
                    active: true,
                    address: 'Helmholtzstraat 57\r\n1098 LE AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: undefined,
                    lines: ['Helmholtzstraat 57'],
                    geolocation: undefined,
                    postalcode: '1098 LE',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '02',
                    display_name: 'Apothekers',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
                {
                    code: 'Z001',
                    display_name: 'Apotheek',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/organization-type',
                },
                {
                    code: 'J8',
                    display_name: 'Openbare apotheek',
                    type: 'http://nictiz.nl/fhir/NamingSystem/organization-type',
                },
            ],
        },
        {
            display_name: 'A.P.T.P.',
            identification_type: 'agb-z',
            identification_value: '94003617',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Kempenlaan 65\r\n1066RA AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Kempenlaan 65'],
                    geolocation: {
                        latitude: 115600,
                        longitude: 484344,
                    },
                    postalcode: '1066RA',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '94',
                    display_name: 'Psychologische Zorgverleners',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'A.P.T.P.',
            identification_type: 'agb-z',
            identification_value: '71073323',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Kempenlaan 65\r\n1066RA AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Kempenlaan 65'],
                    geolocation: {
                        latitude: 115600,
                        longitude: 484344,
                    },
                    postalcode: '1066RA',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '94',
                    display_name: 'Psychologische Zorgverleners',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'A.P. VAN DE BLANKEVOORT-VAN TOL',
            identification_type: 'agb-z',
            identification_value: '96001600',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Bonnefantenstraat 8\r\n1064PN AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Bonnefantenstraat 8'],
                    geolocation: {
                        latitude: 116980,
                        longitude: 486563,
                    },
                    postalcode: '1064PN',
                    state: undefined,
                    type: 'postal',
                },
            ],
            names: [],
            types: [
                {
                    code: '96',
                    display_name: 'Pedicuren',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
        {
            display_name: 'A.P. VAN DE BLANKEVOORT-VAN TOL',
            identification_type: 'agb-z',
            identification_value: '71081066',
            active: true,
            addresses: [
                {
                    active: true,
                    address: 'Bonnefantenstraat 8\r\n1064PN AMSTERDAM',
                    city: 'AMSTERDAM',
                    country: 'NEDERLAND',
                    lines: ['Bonnefantenstraat 8'],
                    geolocation: {
                        latitude: 116980,
                        longitude: 486563,
                    },
                    postalcode: '1064PN',
                    state: undefined,
                    type: 'physical',
                },
            ],
            names: [],
            types: [
                {
                    code: '96',
                    display_name: 'Pedicuren',
                    type: 'http://www.vzvz.nl/fhir/NamingSystem/vektis-zorgsoort',
                },
            ],
        },
    ],
};

export const search = async (_searchQuery: { name: string; city: string }) => {
    await new Promise((resolve) => setTimeout(resolve, Math.random() * 1000 + 500));

    return searchResponse;
};
