name: Fhir-data

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  schemas:
    runs-on: ubuntu-22.04
    name: Check schemas
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Generate new schemas
        working-directory: packages/fhir-data
        run: pnpm build:schemas
      - name: Ensure the most up-to-date schema was committed
        run: |
          if ! git diff --quiet; then
              echo "Changes detected!"
              git diff
              exit 1
          fi
