name: CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run lint

  format:
    runs-on: ubuntu-22.04
    name: Format
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check formatting
        run: pnpm run format:check

  check-types:
    runs-on: ubuntu-22.04
    name: Check types
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check types
        run: pnpm run -r check-types

  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        id: test
        run: pnpm run test:coverage
      - name: Upload coverage report
        if: ${{ !cancelled() && (steps.test.conclusion == 'success' || steps.test.conclusion == 'failure') }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        working-directory: apps/react
        run: pnpm run build
