name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run lint

  format:
    runs-on: ubuntu-22.04
    name: Format
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check formatting
        run: pnpm run format:check

  check-types:
    runs-on: ubuntu-22.04
    name: Check types
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check types
        run: pnpm run check-types

  check-i18n:
    runs-on: ubuntu-22.04
    name: Check i18n
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Extract messages
        working-directory: apps/mgo
        run: pnpm run messages:extract
      - name: Check for changes which should have been in GIT
        run: |
          if [ -z "$(git status -s)" ] ; then echo "no git changes" ; else echo "git changes detected" && git status && git diff && exit 1 ; fi

  test:
    runs-on: ubuntu-22.04
    name: Test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        id: test
        run: pnpm run test:coverage
      - name: Upload coverage report
        if: ${{ !cancelled() && (steps.test.conclusion == 'success' || steps.test.conclusion == 'failure') }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        working-directory: apps/mgo
        run: pnpm run build

  sonar:
    runs-on: ubuntu-22.04
    needs: test
    name: Run SonarCloud scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Download artifact: coverage'
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Run SonarCloud scanner
        uses: minvws/nl-irealisatie-generic-pipelines/.github/actions/sonarcloud@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
