name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-22.04
    name: Build & validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm run lint
      - name: Check formatting
        run: pnpm run format:check
      - name: Check types
        run: pnpm run -r check-types
      - name: Extract messages
        working-directory: apps/react
        run: pnpm run messages:extract
      - name: Check for changes which should have been in GIT
        run: |
          if [ -z "$(git status -s)" ] ; then echo "no git changes" ; else echo "git changes detected" && git status && git diff && exit 1 ; fi
      - name: Test
        id: test
        run: pnpm run test:coverage
      - name: Upload coverage report
        if: ${{ !cancelled() && (steps.test.conclusion == 'success' || steps.test.conclusion == 'failure') }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
      - name: Build
        working-directory: apps/react
        run: pnpm run build
      - name: SonarCloud
        if: always()
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
