name: Run e2e tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      test-command:
        description: 'Command to run the e2e tests'
        required: false
        default: 'pnpm run e2e:ci'
        type: string
jobs:
  mgo-e2e:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-docker-action@v4

      - name: Start Docker containers
        env:
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: docker compose up --build -d

      - name: Run e2e tests
        run: docker exec playwright bash -c "${{ inputs.test-command }}"

      - name: Upload Test Report Chrome
        uses: actions/upload-artifact@v4.6.1
        if: always()
        with:
          name: e2e-playwright-chrome
          path: apps/mgo-e2e/results/

      - name: Stop Docker containers
        if: always()
        run: docker compose down
