name: Run e2e tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      test-command:
        description: 'Run the e2e tests'
        required: false
        default: 'pnpm run e2e:ci'
        type: string
      enable-accessibility-checks:
        description: 'Check on Accessibility'
        required: false
        default: 'false'
        type: string

jobs:
  mgo-e2e:
    runs-on: ubuntu-22.04

    env:
      TEST_COMMAND: ${{ inputs.test-command || 'pnpm run e2e:ci' }}
      ENABLE_ACCESSIBILITY_CHECKS: ${{ inputs.enable-accessibility-checks }}

    steps:
      - name: Free disk space run
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
      - uses: actions/checkout@v6
      - uses: docker/setup-docker-action@v5

      - name: Start Docker containers
        env:
          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: docker compose up --build -d

      - name: Run e2e tests
        run: docker exec playwright bash -c "$TEST_COMMAND"

      - name: Upload Test Report Chrome
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: e2e-playwright-chrome
          path: apps/mgo-e2e/results/
          if-no-files-found: error

      - name: Stop Docker containers
        if: always()
        run: docker compose down --rmi all --volumes --remove-orphans
