name: Package - HCIM API

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/package-hcim-api.yml'
      - 'apps/mgo-hcim-api/**'
      - 'packages/hcim/**'
      - 'packages/hcim-ui/**'
      - 'packages/hcim-parse/**'
      - 'packages/intl/src/locales/fhir/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/package
        with:
          package-path: 'apps/hcim-api'
