name: Create release package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Update i18n files
        working-directory: packages/mgo-intl
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID_MGO_APP: ${{ secrets.LOKALISE_PROJECT_ID_MGO_APP }}
          LOKALISE_PROJECT_ID_MGO_FHIR: ${{ secrets.LOKALISE_PROJECT_ID_MGO_FHIR }}
        run: pnpm run messages:update
      - name: Build
        working-directory: apps/mgo
        run: pnpm run build
      - name: Add version.json
        shell: bash
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > apps/mgo/dist/version.json'
      - name: Create release tar
        run: tar -C apps/mgo/dist -czf nl-mgo-app-web_${{ env.RELEASE_VERSION }}.tar.gz .
      - name: Upload release tar
        uses: actions/upload-artifact@v4
        with:
          name: nl-mgo-app-web_${{ env.RELEASE_VERSION }}
          path: nl-mgo-app-web_${{ env.RELEASE_VERSION }}.tar.gz
